name: ApexPrison
main: eu.apexmc.prison.main.Main
version: 1.0
authors: [HeriPutr, 4p3x]
website: apexmc.eu
commands:
    apex:
        description: ApexPrison base command.
        usage: /<command>
    block:
        description: Block grouping command.
        usage: /<command>
    cc:
        description: Admin chat clear command.
        usage: /<command>
    smelt:
        description: Ore smelting command.
        usage: /<command>